version: "3"

services:

    # Production (RoadRunner)
    amdb:
        build:
            context: /var/html/docker
            dockerfile: rr.Dockerfile
        ports:
            - 8088:8090
        volumes:
            - .:/var/www/html

    # Development (Nginx & FPM)
    amdb-dev:
        build:
            context: /var/html/docker
            dockerfile: nginx.Dockerfile
        ports:
            - 8087:80
        volumes:
            - .:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - amdb-dev-fpm

    amdb-dev-fpm:
        build:
            context: /var/html/docker
            dockerfile: php8.Dockerfile
        volumes:
            - .:/var/www/html

networks:
    default:
        external:
            name: nginx
